public with sharing class Test1 {
	public Test1() {
		//this is a change for the newbranch1
		//this is another change


		//now I'm making a change on the master while I have a branch Story12345
		

		//I'm making this change for branch Story12345!!

		//Making a second change for the new branch Story12345

		//Making a change on branch Story12345 while the branch is remote

		//Removing some crap and making a change on the master again 

		//This is a change, on the task branch


	}
}